name: Manual maven steps for ci
on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  manual:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build package
        run: mvn clean verify --batch-mode

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/target/surefire-reports/*.xml
            **/target/failsafe-reports/*.xml

      - name: Upload packaged JAR files
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-${{ matrix.java }}
          path: '**/target/*.jar'

      - name: Send email on failure
        run: echo "everything seems problematic"
        if: ${{ failure() }}

      - name: Send email on success
        run: echo "everything seems fun"
        if: ${{ success() }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-test-results
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
